<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xojo_code</string>
		<string>xojo_window</string>
		<string>xojo_menu</string>
		<string>xojo_report</string>
		<string>xojo_script</string>
		<string>xojo_toolbar</string>
		<string>xojo_image</string>
		<string>rbbas</string>
		<string>rbfrm</string>
		<string>rbmnu</string>
		<string>rbres</string>
		<string>rbtbar</string>
	</array>
	<key>name</key>
	<string>xojo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-rem</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords-numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords-functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers-literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers-binary</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(//|').*$</string>
			<key>name</key>
			<string>punctuation.definition.comment.xojo</string>
		</dict>
		<key>comment-rem</key>
		<dict>
			<key>match</key>
			<string>(?i)(rem .++)$</string>
			<key>name</key>
			<string>punctuation.definition.comment.xojo</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(me|self|super|return|dim|var|const|static|as|if|then|else|elseif|for|next|do|loop|until|while|wend|end if|select case|case|end select|private|public|protected|inherits|try|catch|finally|nil|and|or|not|mod|to|downto|new|get|set|end)\b</string>
			<key>name</key>
			<string>keyword.xojo</string>
		</dict>
		<key>directives</key>
		<dict>
			<key>match</key>
			<string>(?i)#(if|else|elseif|endif|pragma)\b</string>
			<key>name</key>
			<string>keyword.xojo</string>
		</dict>
		<key>keywords-functions</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(sub|function|class|return|begin)\s\w++\b</string>
			<key>name</key>
			<string>keyword.xojo</string>
		</dict>
		<key>keywords-numeric</key>
		<dict>
			<key>match</key>
			<string>\b(?i)(boolean|integer|double|cgfloat|long|string|color|true|false|(u)*int(8|16|32|64))\b</string>
			<key>name</key>
			<string>keyword.xojo</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\b(-)?[0-9.]+\b</string>
			<key>name</key>
			<string>constant.numeric.xojo</string>
		</dict>
		<key>numbers-literal</key>
		<dict>
			<key>match</key>
			<string>(?i)(&amp;h|&amp;c)[0-9a-f]+</string>
			<key>name</key>
			<string>constant.numeric.integer</string>
		</dict>
		<key>numbers-binary</key>
		<dict>
			<key>match</key>
			<string>(?i)&amp;b[01]+</string>
			<key>name</key>
			<string>constant.numeric.integer</string>
		</dict>
		<key>string-literal</key>
		<dict>
			<key>comment</key>
			<string>string literals</string>
			<key>match</key>
			<string>(\".*?\")</string>
			<key>name</key>
			<string>string.quoted.double.xojo</string>
		</dict>
		<key>tags</key>
		<dict>
			<key>match</key>
			<string>^\s*#tag.*$</string>
			<key>name</key>
			<string>markup.bold.xojo</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.xojo</string>
	<key>uuid</key>
	<string>01a14c39-92f7-44be-aee7-9dd38e59d7e9</string>
</dict>
</plist>
